version: '3.3'
services:
  mux:
    build: mux
    env_file: .env
    restart: always
    command: npm start
    depends_on:
      - logoutput
      - logerrors
      - notlogged
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace/dlogmux/logs:/mnt
  logoutput:
    image: ubuntu
    env_file: .env
    labels:
      - $LOG_STRATEGY_KEY=LOG
    command:  bash -c 'ID=0; while true; do ((ID++));printf "%06d-" "$ID"; hostname;  sleep 10; done'  
  logerrors:
    image: ubuntu
    env_file: .env
    labels:
      - $LOG_STRATEGY_KEY=LOG
    command: bash -c 'ID=0; while true; do ((ID++)); printf "%06d-" "$ID"; echo -n `hostname`" " && ping nobody; sleep 10; done'
  notlogged:
    image: ubuntu
    env_file: .env
    command: bash -c 'ID=0; while true; do ((ID++));printf "%06d-" "$ID"; echo "If you see this in the logfile in $HOST_LOGFILE_DIR something is wrong";  sleep 10; done'             
  