version: '3.3'
services:
  mux:
    build: mux
    env_file: .env
    restart: always
    command: npm start
    depends_on:
      - logoutput
      - logerrors
      - notlogged
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace/dlogmux/logs:/mnt
  logoutput:
    image: ubuntu
    env_file: .env
    labels:
      - $LOG_STRATEGY_KEY=LOG
    command:  bash -c 'NUM=0; while true; do ((NUM++));printf "%06d-" "$$NUM"; hostname;  sleep 10; done'  
  logerrors:
    image: ubuntu
    env_file: .env
    labels:
      - $LOG_STRATEGY_KEY=LOG
    command: bash -c 'while true; do ping nobody; sleep 10; done'
  # logmix:
  #   image: ubuntu
  #   env_file: .env
  #   labels:
  #     - $LOG_STRATEGY_KEY=LOG
  #   command: bash -c 'NUM=0; while true; do ((NUM++)); printf "%06d-" "$$NUM"; echo -n `hostname`" " && grep 1234567 abcdefg; sleep 10; done'
  notlogged:
    image: ubuntu
    env_file: .env
    command: bash -c 'NUM=0; while true; do ((NUM++));printf "%06d-" "$$NUM"; echo -n `hostname`; echo " This should not appear in $HOST_LOGFILE_DIR/messages";  sleep 10; done'             
  